fullnameOverride: "lops"
nameOverride: "lops"

appName: "lops"
appType: "api"
team: "platform"
environment: "local"

podLabels:

replicaCount: 1

autoscaling:
  enabled: false

image:
  repository: "charmingruby/lops"
  tag: "latest"
  pullPolicy: "Always"

service:
  port: 3000

config:
  hasConfigMap: true
  configMapData:
    DUMMY_SECRET: "some-secret"
    REST_SERVER_PORT: "3000"

livenessProbe:
  httpGet:
    path: /api/v1/health/live
    port: 3000
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /api/v1/health/ready
    port: 3000
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

resources:
  limits:
    cpu: "500m"
    memory: "256Mi"
  requests:
    cpu: "250m"
    memory: "128Mi"
