apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nameOverride }}-service
  labels:
    {{- include "base.metadata" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "base.selectorLabels" . | nindent 4 }}
