apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: lops-api
    namespace: argocd
spec:
    project: default

    source:
        repoURL: https://github.com/charmingruby/lops.git
        targetRevision: HEAD
        path: .

    destination:
        server: https://kubernetes.default.svc
        namespace: lops-api-applicatioon
    syncPolicy:
        syncOptions:
            - CreateNamespace=true
        automated:
            selfHeal: true
            prune: true
