replicaCount: 2

image:
  repository: my-registry/lops
  tag: "1.0.0"
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 80

resources: {}
#   limits:
#     cpu: 500m
#     memory: 512Mi
#   requests:
#     cpu: 250m
#     memory: 256Mi

livenessProbe: {}
#   httpGet:
#     path: /healthz
#     port: http
#   initialDelaySeconds: 5
#   periodSeconds: 10

readinessProbe: {}
#   httpGet:
#     path: /ready
#     port: http
#   initialDelaySeconds: 5
#   periodSeconds: 10

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}

volumes: []
volumeMounts: []
